@startuml
hide empty description


[*] -right> defaultState
defaultState -right-> stateN : Received DSC request\nwith parameter n

stateN -left->  defaultState : timeout

state "state n" as stateN {
  state Locked
  state Unlocked
  [*] -> Locked
  Locked --> Unlocked : SA\nhandshake
  Unlocked --> Locked
}
@enduml
